### ISSUE TITLE
求教，clone之后无法npm构建是怎么回事？

### ISSUE THREAD

**Issue by maodou38** [danbaixi/hourse-slave#1]
![image](https://user-images.githubusercontent.com/39987981/132270867-6e658e79-e7f0-4ea1-81db-f91d2e5cfaa5.png)

**Comment by danbaixi** [comment]
忘记加了一个步骤，要修改project.config.json，按照下面这样修改：
`{
  ...
  "setting": {
    ...
    "packNpmManually": true,
    "packNpmRelationList": [
      {
        "packageJsonPath": "./package.json",
        "miniprogramNpmDistDir": "./miniprogram/"
      }
    ]
  }
}`
完整的参考vant官方文档https://vant-contrib.gitee.io/vant-weapp/#/quickstart#bu-zou-san-xiu-gai-project.config.json

**Comment by danbaixi** [comment]
```json
{
  ...
  "setting": {
    ...
    "packNpmManually": true,
    "packNpmRelationList": [
      {
        "packageJsonPath": "./package.json",
        "miniprogramNpmDistDir": "./miniprogram/"
      }
    ]
  }
}
```

**Comment by maodou38** [comment]
OK OK。学习学习，看看能不能借鉴借鉴

**Comment by maodou38** [comment]
再指导下，npm编译完成了。ps: miniprogram文件夹你也没传
![image](https://user-images.githubusercontent.com/39987981/132272134-3487c7b1-ecb9-48fc-99bc-be66eff27e87.png)
![image](https://user-images.githubusercontent.com/39987981/132272147-42d1c7de-4934-426c-8f48-503eab5e42f1.png)
依旧找不到，有什么特殊配置嘛

**Comment by maodou38** [comment]
得使用相对路径嘛？

**Comment by danbaixi** [comment]
我错了，你现在把miniprogram文件夹删了，把project.config.json改回来，改成：
```json
    "packNpmManually": false,
    "packNpmRelationList": []
```
然后在命令行执行npm install 就会生成一个miniprogram_npm文件夹，然后就可以运行了

**Comment by maodou38** [comment]
好了 原谅一个没怎么搞过小程序的后端工程师被shit了。敢情我就是没npm install而已，居然质疑了你的上传代码:smile:
