### ISSUE TITLE
搜索页面有异常

### ISSUE THREAD

**Issue by zooPanda** [danbaixi/hourse-slave#2]
具体看视频。
搜索页面在快速搜索的状态下，详细搜索的输入框会穿透出来。

https://user-images.githubusercontent.com/85251910/132806845-2dd8da48-e3c8-4ee7-bc60-d29c7ffe2d99.MOV

**Comment by danbaixi** [comment]
我用我手机iphone11，和模拟器试了都没问题，你的手机型号是什么

**Comment by zooPanda** [comment]
iPhone 12、iphone 12 Pro。
微信版本 8.0.13

蛋白熙 ***@***.***>于2021年9月10日 周五14:25写道：

**Comment by danbaixi** [comment]
我还是没复现出来。。。

**Comment by zooPanda** [comment]
> 我还是没复现出来。。。

把小程序删除重新搜索还是一样。

https://user-images.githubusercontent.com/85251910/132815743-aaff17fc-d38a-4fe9-a7c8-90730c5c7441.MOV

**Comment by zooPanda** [comment]
iPhone 12 Pro Max无法复现，现在手头其他没别的机器测试了。

**Comment by danbaixi** [comment]
这个问题在新版本应该解决了。

**Comment by zooPanda** [comment]
近期使用iPhone 13 mini，iOS 15.0.1，WeChat 8.0.14已经没有再遇见这个问题了。
话说看了作者的项目，也学习尝试自己写了一个我们当地的房产备案信息查询小工具。
岩房
谢谢大佬的创意。
